
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import subprocess

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("RX4U")

window.geometry("584x411")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 411,
    width = 584,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    236.0,
    36.0,
    anchor="nw",
    text="RX4U",
    fill="#FFFFFF",
    font=("Inter Bold", 40 * -1)
)

canvas.create_rectangle(
    25.0,
    129.0,
    552.0,
    135.0,
    fill="#FFFFFF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: subprocess.run(["python3", "gui1.py"]),
    relief="flat"
)
button_1.place(
    x=215.0,
    y=188.0,
    width=153.0,
    height=38.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: subprocess.run(["python3", "gui2.py"]),
    relief="flat"
)
button_2.place(
    x=215.0,
    y=266.0,
    width=153.0,
    height=38.0
)
window.resizable(False, False)
window.mainloop()