
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import json
from tkinter import messagebox

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame1")

def save_inputs():
    # Get the user's inputs
    name = entry_1.get()
    dob = entry_2.get()
    medication = entry_3.get()
    quantity = entry_4.get()

    # Validate the inputs
    if not name:
        messagebox.showerror("Error", "Name field is empty.")
        return
    if not dob:
        messagebox.showerror("Error", "DOB field is empty.")
        return
    if not medication:
        messagebox.showerror("Error", "Medication field is empty.")
        return
    if not quantity.isdigit():
        messagebox.showerror("Error", "Quantity field is not a number.")
        return

    # Load the existing data from the JSON file
    try:
        with open('data.json', 'r') as file:
            data = json.load(file)
    except (FileNotFoundError, json.JSONDecodeError):
        data = []

    # Append the new data
    data.append({
        'name': name,
        'dob': dob,
        'medication': medication,
        'quantity': quantity,
    })

    # Save the data back to the JSON file
    try:
        with open('data.json', 'w') as file:
            json.dump(data, file, indent=4)
    except Exception as e:
        messagebox.showerror("Error", f"An error occurred while saving the data: {e}")
        return
    
    window.destroy()




def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("RX4U")

window.geometry("584x411")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 411,
    width = 584,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    236.0,
    36.0,
    anchor="nw",
    text="RX4U",
    fill="#FFFFFF",
    font=("Inter Bold", 40 * -1)
)

canvas.create_rectangle(
    25.0,
    129.0,
    552.0,
    135.0,
    fill="#FFFFFF",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    201.0,
    215.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=128.0,
    y=202.0,
    width=146.0,
    height=25.0
)

canvas.create_text(
    128.0,
    186.0,
    anchor="nw",
    text="Name",
    fill="#FFFFFF",
    font=("Inter Bold", 13 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    382.0,
    215.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=309.0,
    y=202.0,
    width=146.0,
    height=25.0
)

canvas.create_text(
    309.0,
    186.0,
    anchor="nw",
    text="DOB",
    fill="#FFFFFF",
    font=("Inter Bold", 13 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    201.0,
    285.5,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=128.0,
    y=272.0,
    width=146.0,
    height=25.0
)

canvas.create_text(
    128.0,
    256.0,
    anchor="nw",
    text="Medication",
    fill="#FFFFFF",
    font=("Inter Bold", 13 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    382.0,
    285.5,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=309.0,
    y=272.0,
    width=146.0,
    height=25.0
)

canvas.create_text(
    309.0,
    256.0,
    anchor="nw",
    text="Quantity",
    fill="#FFFFFF",
    font=("Inter Bold", 13 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: save_inputs(),
    relief="flat"
)
button_1.place(
    x=215.0,
    y=326.0,
    width=153.0,
    height=38.0
)
window.resizable(False, False)
window.mainloop()