
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import json
from tkinter import messagebox


# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame2")

def search_data():
    name = entry_1.get().strip()
    dob = entry_2.get().strip()

    # Validate input
    if not name or not dob:
        messagebox.showerror("Error", "Please provide both name and date of birth.")
        return

    # Read data from JSON file
    try:
        with open('data.json', 'r') as file:
            data = json.load(file)
    except Exception as e:
        messagebox.showerror("Error", f"An error occurred while reading the data: {e}")
        return

    # Search for user
    for user in data:
        if user['name'] == name and user['dob'] == dob:
            messagebox.showinfo("Search result", f"Medication: {user['medication']}\nQuantity: {user['quantity']}")
            return

    # If function hasn't returned by now, the user wasn't found
    messagebox.showinfo("Search result", "No user found with the provided name and date of birth.")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("RX4U")

window.geometry("584x411")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 411,
    width = 584,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    236.0,
    36.0,
    anchor="nw",
    text="RX4U",
    fill="#FFFFFF",
    font=("Inter Bold", 40 * -1)
)

canvas.create_rectangle(
    25.0,
    129.0,
    552.0,
    135.0,
    fill="#FFFFFF",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    201.0,
    215.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=128.0,
    y=202.0,
    width=146.0,
    height=25.0
)

canvas.create_text(
    128.0,
    186.0,
    anchor="nw",
    text="Name",
    fill="#FFFFFF",
    font=("Inter Bold", 13 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    382.0,
    215.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=309.0,
    y=202.0,
    width=146.0,
    height=25.0
)

canvas.create_text(
    309.0,
    186.0,
    anchor="nw",
    text="DOB",
    fill="#FFFFFF",
    font=("Inter Bold", 13 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: search_data(),
    relief="flat"
)
button_1.place(
    x=215.0,
    y=280.0,
    width=153.0,
    height=38.0
)
window.resizable(False, False)
window.mainloop()
